---
sidebar: sidebar
permalink: task-manage-volumes.html
keywords: google cloud netapp volumes, view volumes
summary: After you set up your working environment, you can view your Google Cloud NetApp volumes.
---

= Manage existing volumes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can view your existing volumes and any actions you performed on them.

== View a volume

View the details of your volumes, including their name, count, region, capacity, and used capacity.

.Steps

. Click *Enter working environment* to open the working environment.
You can view all your volume details including the name, region, capacity, and used capacity.

. To view a specific volume in the table, select "search icon" and enter the volume name.

. To view any labels associated with a volume, in the *Labels* column, select *View*.

== View the audit log

You can view all the actions performed on volumes in the timeline.

.Steps

. How to get to page.?

. At the top right, select *Settings* > *Timeline*.

.Result

In the *Audit logs* table, you can view any actions performed on your volumes.
